version: 2

models:
  - name: stg_product
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: site
        tests: [not_null]
      - name: url
        tests: [not_null, unique]

  - name: stg_price_history
    columns:
      - name: id
        tests: [not_null, unique]
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_product')
              field: product_id
      - name: ts_utc
        tests: [not_null]
      - name: price
        tests: []
